2021-04-14 16:33:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 29.60)
2021-04-14 16:33:05 - eVOLVER - [INFO] - setting initial OD reading
2021-04-14 16:33:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 29.54)
2021-04-14 16:33:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 29.54)
2021-04-14 16:34:04 - eVOLVER - [WARNING] - interrupt received, pausing experiment
2021-04-14 16:34:04 - eVOLVER - [INFO] - stopping all pumps
2021-04-14 16:34:04 - eVOLVER - [WARNING] - second interrupt received, terminating experiment
2021-04-14 16:34:04 - eVOLVER - [INFO] - stopping all pumps
2021-04-14 16:34:04 - eVOLVER - [WARNING] - experiment stopped, goodbye!
2021-04-14 16:34:04 - eVOLVER - [INFO] - stopping all pumps
2021-04-14 16:34:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 29.54)
2021-04-14 16:34:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 29.51)
2021-04-14 16:35:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 29.46)
2021-04-14 16:35:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 29.16)
2021-04-14 16:35:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 28.52)
2021-04-14 16:36:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 27.90)
2021-04-14 16:36:05 - custom_script - [INFO] - turbidostat dilution for vial 2
2021-04-14 16:36:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 27.17)
2021-04-14 16:36:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 26.44)
2021-04-14 16:37:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 25.77)
2021-04-14 16:37:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 24.97)
2021-04-14 16:37:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 24.24)
2021-04-14 16:38:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.60)
2021-04-14 16:38:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 22.87)
2021-04-14 16:38:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 22.22)
2021-04-14 16:39:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 21.58)
2021-04-14 16:39:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 21.08)
2021-04-14 16:39:25 - custom_script - [INFO] - turbidostat dilution for vial 2
2021-04-14 16:39:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 20.41)
2021-04-14 16:40:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 19.76)
2021-04-14 16:40:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 19.35)
2021-04-14 16:40:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 18.82)
2021-04-14 16:41:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 18.30)
2021-04-14 16:41:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 17.77)
2021-04-14 16:41:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 17.39)
2021-04-14 16:42:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 16.95)
2021-04-14 16:42:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 16.66)
2021-04-14 16:42:25 - custom_script - [INFO] - turbidostat dilution for vial 2
2021-04-14 16:42:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 16.25)
2021-04-14 16:43:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 15.84)
2021-04-14 16:43:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 15.66)
2021-04-14 16:43:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 15.37)
2021-04-14 16:44:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 15.05)
2021-04-14 16:44:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 14.75)
2021-04-14 16:44:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 14.52)
2021-04-14 16:45:06 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 14.23)
2021-04-14 16:45:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 13.96)
2021-04-14 16:45:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 13.79)
2021-04-14 16:45:45 - custom_script - [INFO] - turbidostat dilution for vial 2
2021-04-14 16:46:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 13.52)
2021-04-14 16:46:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 13.38)
2021-04-14 16:46:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 13.26)
2021-04-14 16:47:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 13.06)
2021-04-14 16:47:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 12.94)
2021-04-14 16:47:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 12.85)
2021-04-14 16:48:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 12.79)
2021-04-14 16:48:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 12.62)
2021-04-14 16:48:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 12.67)
2021-04-14 16:48:45 - custom_script - [INFO] - turbidostat dilution for vial 2
2021-04-14 16:49:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 12.59)
2021-04-14 16:49:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 12.38)
2021-04-14 16:49:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 12.26)
2021-04-14 16:50:04 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 12.06)
2021-04-14 16:50:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.83)
2021-04-14 16:50:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.68)
2021-04-14 16:51:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.62)
2021-04-14 16:51:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.56)
2021-04-14 16:51:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.53)
2021-04-14 16:51:46 - custom_script - [INFO] - turbidostat dilution for vial 2
2021-04-14 16:52:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.47)
2021-04-14 16:52:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.33)
2021-04-14 16:52:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.33)
2021-04-14 16:53:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.30)
2021-04-14 16:53:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.21)
2021-04-14 16:53:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.24)
2021-04-14 16:54:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.12)
2021-04-14 16:54:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.15)
2021-04-14 16:54:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.06)
2021-04-14 16:55:04 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.06)
2021-04-14 16:55:05 - custom_script - [INFO] - turbidostat dilution for vial 2
2021-04-14 16:55:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.03)
2021-04-14 16:55:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.01)
2021-04-14 16:56:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 11.01)
2021-04-14 16:56:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 10.86)
2021-04-14 16:57:35 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [connection error] recv disconnected ([Errno 60] Operation timed out)
2021-04-14 16:57:36 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [connection error] recv disconnected ([Errno 60] Operation timed out)
2021-04-14 16:58:51 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618433856824-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e0b8>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:00:07 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618433932896-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cd68>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:00:08 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434008961-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c550>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:00:09 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434009972-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6588>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:00:10 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434010981-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6358>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:00:11 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434011990-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6c50>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:00:13 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434013001-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c15f8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:00:14 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434014008-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cac8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:30 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434015012-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c518>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:01:31 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434091091-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c208>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:32 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434092096-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c978>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:33 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434093105-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6f28>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:34 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434094113-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d69b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:35 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434095122-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6fd0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:36 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434096127-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1400>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:37 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434097135-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c12b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:38 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434098139-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1550>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:39 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434099149-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ecc0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:01:40 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434100157-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2a58>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:02:56 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434101166-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1160>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:02:57 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434177231-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c10b8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:02:58 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434178242-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1a58>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:02:59 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434179250-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6860>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:03:00 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434180258-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6ba8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:03:01 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434181266-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6c50>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:03:02 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434182274-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e908>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:03:03 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434183281-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ec88>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:03:04 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434184290-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c160>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:03:05 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434185295-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ca90>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:04:21 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434186299-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c2e8>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:04:22 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434262368-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c13c8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:04:23 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434263378-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2cc0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:04:24 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434264383-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c780>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:04:25 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434265391-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cd68>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:05:41 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434266397-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c128>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:05:42 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434342457-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ec50>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:05:43 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434343466-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e198>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:05:44 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434344475-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6e48>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:05:45 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434345482-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6048>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:05:46 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434346490-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d64e0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:05:47 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434347498-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d69b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:05:48 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434348506-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c12e8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:04 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434349514-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1898>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:07:05 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434425598-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d24a8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:06 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434426607-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2a90>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:07 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434427612-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1198>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:08 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434428621-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c10f0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:09 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434429630-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1470>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:10 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434430639-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6d68>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:11 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434431647-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6828>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:12 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434432655-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6518>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:13 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434433660-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ee10>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:14 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434434671-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e908>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:15 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434435679-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ec50>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:07:16 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434436684-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c128>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:08:32 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434437697-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c048>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:08:33 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434513771-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c780>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:08:34 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434514783-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d21d0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:08:35 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434515789-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d24a8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:08:36 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434516801-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ca58>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:08:37 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434517807-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ce48>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:08:38 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434518817-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c940>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:08:39 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434519825-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e898>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:08:40 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434520833-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e860>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:09:56 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434521841-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d65f8>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:09:57 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434597937-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6b38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:09:58 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434598941-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6128>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:09:59 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434599953-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1470>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:10:00 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434600957-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1e48>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:10:01 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434601962-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1390>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:18 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434602967-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cc50>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:11:19 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434679064-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2048>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:20 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434680074-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1a90>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:21 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434681079-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1b00>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:22 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434682082-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d60f0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:23 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434683090-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6ef0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:24 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434684098-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6358>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:25 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434685106-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6cf8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:26 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434686115-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e9b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:27 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434687124-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ef98>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:28 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434688132-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c8d0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:29 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434689137-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ceb8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:11:30 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434690149-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c240>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:12:46 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434691158-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2b00>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:12:47 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434767245-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d28d0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:12:48 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434768257-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c0b8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:12:49 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434769262-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c128>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:05 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434770270-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ccc0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:14:06 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434846345-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ee48>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:07 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434847351-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e860>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:08 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434848355-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ec18>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:09 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434849363-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6ac8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:10 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434850369-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6588>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:11 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434851375-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1240>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:12 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434852380-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1518>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:13 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434853386-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1f28>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:14 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434854391-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d25f8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:14:15 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434855395-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3ba8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:15:31 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434856403-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6940>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:15:32 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434932492-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6e80>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:15:33 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434933498-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d60b8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:15:34 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434934502-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ccf8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:15:35 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434935512-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c438>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:15:36 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434936518-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c828>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:15:37 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434937527-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e978>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:15:38 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434938537-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40eeb8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:15:39 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434939546-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2470>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:15:40 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434940550-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2be0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:16:56 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618434941558-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2198>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:16:57 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435017633-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1160>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:16:58 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435018638-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2dd8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:16:59 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435019650-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2cf8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:17:00 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435020661-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d26a0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:18:16 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435021666-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ea20>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:18:17 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435097759-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e9b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:18:18 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435098766-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d60b8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:18:19 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435099779-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6b00>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:18:20 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435100788-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d66d8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:18:21 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435101799-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c5f8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:18:22 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435102805-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cc18>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:19:38 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435103813-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c898>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:19:39 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435179892-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1710>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:19:40 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435180897-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c16d8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:19:41 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435181901-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1128>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:19:42 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435182912-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c9b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:19:43 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435183925-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cdd8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:19:44 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435184934-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c6d8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:19:45 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435185943-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6940>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:21:02 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435186954-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6e80>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:21:03 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435263030-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6518>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:21:04 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435264038-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6898>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:21:05 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435265046-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e978>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:21:06 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435266051-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d26a0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:21:07 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435267060-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2828>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:21:08 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435268070-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2d68>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:21:09 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435269078-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1f60>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:21:10 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435270088-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3da0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:26 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435271096-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1da0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:22:27 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435347191-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d24e0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:28 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435348198-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d24a8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:29 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435349203-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40edd8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:30 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435350213-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e470>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:31 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435351217-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6518>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:32 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435352226-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d62e8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:33 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435353238-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d69b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:34 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435354248-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c6d8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:35 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435355257-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ce80>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:36 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435356265-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c518>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:37 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435357270-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3e48>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:38 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435358276-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3860>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:22:39 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435359281-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ca90>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:23:55 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435360287-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cb70>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:23:56 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435436371-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c630>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:23:57 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435437376-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6160>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:23:58 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435438381-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6b00>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:23:59 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435439390-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6198>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:24:00 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435440398-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e438>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:24:01 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435441401-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e198>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:24:02 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435442411-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2470>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:24:03 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435443422-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2be0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:24:04 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435444429-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1630>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:24:05 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435445437-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3358>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:24:06 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435446450-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3550>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:24:07 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435447462-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1630>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:24:08 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435448467-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d23c8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:25:24 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435449472-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d26a0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:25:25 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435525542-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40eb38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:25:26 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435526553-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40eac8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:25:27 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435527558-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6978>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:25:28 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435528567-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6ba8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:25:29 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435529578-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40efd0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:25:30 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435530587-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d64a8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:25:31 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435531595-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c550>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:26:47 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435532608-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c048>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:26:48 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435608679-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cf60>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:26:49 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435609687-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3c88>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:26:50 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435610697-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cb38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:26:51 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435611704-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c5c0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:26:52 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435612713-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c6a0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:26:53 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435613724-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6438>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:26:54 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435614731-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d64e0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:26:55 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435615740-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6240>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:26:56 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435616744-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ef98>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:28:12 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435617754-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e978>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:28:13 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435693834-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2c18>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:28:14 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435694840-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2748>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:28:15 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435695848-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c18d0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:28:16 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435696856-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a32b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:28:17 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435697864-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48dd68>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:28:18 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435698872-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1470>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:29:35 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435699876-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1898>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:29:36 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435776023-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2860>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:29:37 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435777027-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d28d0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:29:38 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435778031-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40eb38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:29:39 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435779037-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e9e8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:29:40 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435780045-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6588>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:29:41 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435781051-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d66d8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:29:42 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435782057-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6f60>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:29:43 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435783065-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c6d8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:29:44 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435784073-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c390>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:31:00 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435785080-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ca20>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:31:01 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435861186-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d7b8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:31:02 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435862190-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c048>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:31:03 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435863196-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cef0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:31:04 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435864202-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6748>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:31:05 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435865210-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6438>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:31:06 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435866214-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6208>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:31:07 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435867220-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ee48>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:31:08 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435868224-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40eb38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:31:09 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435869227-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d25f8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:32:25 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435870233-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6828>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:32:26 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435946327-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2668>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:32:27 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435947331-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3278>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:32:28 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435948336-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1278>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:32:29 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435949342-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d5f8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:32:30 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435950346-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3ef0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:32:31 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435951350-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2550>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:47 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618435952354-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d24a8>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:33:48 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436028459-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ecf8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:49 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436029463-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40ef60>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:50 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436030471-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6710>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:51 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436031476-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6550>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:52 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436032483-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6898>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:53 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436033487-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ceb8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:54 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436034496-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cbe0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:55 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436035503-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cb38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:56 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436036509-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d898>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:57 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436037516-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ca90>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:58 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436038524-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cd30>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:33:59 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436039532-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cd68>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:34:00 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436040539-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c0f0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:16 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436041547-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d69e8>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:35:17 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436117659-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6240>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:18 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436118667-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e940>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:19 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436119679-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40eb38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:20 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436120687-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d27f0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:21 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436121695-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2e80>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:22 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436122707-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2048>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:23 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436123712-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1c50>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:24 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436124718-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d240>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:25 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436125729-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4c1cf8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:26 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436126738-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2710>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:27 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436127747-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2630>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:28 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436128755-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e978>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:29 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436129765-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40eef0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:30 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436130769-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6f98>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:35:31 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436131778-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6b38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:47 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436132787-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6ba8>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:36:48 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436208875-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c278>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:49 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436209886-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c6a0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:50 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436210894-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2160>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:51 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436211903-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cbe0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:52 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436212911-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48dfd0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:53 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436213919-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d940>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:54 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436214924-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48de48>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:55 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436215934-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48def0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:56 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436216943-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3780>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:57 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436217955-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a38d0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:58 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436218959-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a35c0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:36:59 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436219967-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6940>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:37:00 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436220973-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6ac8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:37:01 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436221985-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6780>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:37:02 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436222995-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d24a8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:19 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436224000-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2390>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:38:20 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436300137-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2128>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:21 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436301147-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42c780>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:22 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436302154-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cb70>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:23 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436303161-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2dd8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:24 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436304172-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d25f8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:25 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436305177-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6710>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:26 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436306182-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d69b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:27 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436307186-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6e80>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:28 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436308196-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3c18>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:29 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436309209-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a36d8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:30 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436310218-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3588>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:31 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436311225-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3b70>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:32 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436312237-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d2b0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:33 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436313241-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d2e8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:38:34 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436314245-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d7f0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:39:50 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436315256-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42ce10>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:39:51 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436391373-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48da58>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:39:52 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436392387-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d1d0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:39:53 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436393399-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d518>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:39:54 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436394404-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3a90>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:10 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436395415-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3ac8>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:41:11 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436471502-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a37f0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:12 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436472511-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d62e8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:13 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436473520-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d67f0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:14 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436474531-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d67b8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:15 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436475538-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2e80>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:16 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436476547-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3b38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:17 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436477559-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2630>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:18 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436478570-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cac8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:19 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436479579-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2cf8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:20 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436480588-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2f60>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:21 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436481595-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6518>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:22 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436482600-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6470>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:41:23 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436483610-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d60f0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:39 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436484623-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a37f0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:42:40 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436560694-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3128>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:41 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436561707-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3e80>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:42 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436562716-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48dfd0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:43 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436563725-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d6a0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:44 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436564731-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d320>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:45 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436565736-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f42cc50>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:46 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436566745-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40efd0>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:47 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436567756-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48de10>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:48 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436568764-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d240>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:49 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436569772-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48df28>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:50 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436570777-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a39e8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:51 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436571787-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d518>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:52 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436572798-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3dd8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:42:53 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436573806-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3668>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:44:09 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436574812-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6f28>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:44:10 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436650883-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6b38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:44:11 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436651890-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6908>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:44:12 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436652901-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d20b8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:44:13 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436653911-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2dd8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:44:14 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436654917-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40eb38>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:44:15 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436655930-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2ba8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:44:16 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436656935-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d2550>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:44:17 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436657944-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6550>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:44:18 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436658952-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d62e8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:45:35 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436659960-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6860>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:45:36 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436736030-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3c18>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:45:37 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436737035-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a34a8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:45:38 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436738047-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3a20>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:45:39 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436739057-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d278>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:45:40 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436740068-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48da20>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:45:41 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436741072-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d748>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:45:42 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436742084-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48de10>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:46:58 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436743092-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f40e940>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2021-04-14 17:46:59 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436819177-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d4a8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:47:00 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436820187-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48df98>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:47:01 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436821194-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f48d518>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:47:02 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436822203-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3390>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:47:03 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436823207-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a3e48>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:47:04 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436824212-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4a32e8>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:47:05 - socketIO-client - [WARNING] - 192.168.1.2:8081/socket.io [engine.io waiting for connection] HTTPConnectionPool(host='192.168.1.2', port=8081): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1618436825216-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11f4d6d68>: Failed to establish a new connection: [Errno 64] Host is down',))
2021-04-14 17:47:41 - eVOLVER - [INFO] - resetting connection to eVOLVER to avoid potential buildup of broadcast messages
2021-04-14 17:47:41 - eVOLVER - [INFO] - reconnected to eVOLVER as client
2021-04-14 17:47:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 29.40)
2021-04-14 17:48:06 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 29.25)
2021-04-14 17:48:26 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 28.87)
2021-04-14 17:48:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 28.31)
2021-04-14 17:49:06 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 27.64)
2021-04-14 17:49:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 26.85)
2021-04-14 17:49:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 26.12)
2021-04-14 17:49:46 - custom_script - [INFO] - turbidostat dilution for vial 2
2021-04-14 17:50:06 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 25.36)
2021-04-14 17:50:26 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 24.65)
2021-04-14 17:50:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.89)
2021-04-14 17:51:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.16)
2021-04-14 17:51:26 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 22.49)
2021-04-14 17:51:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 22.84)
2021-04-14 17:52:06 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.04)
2021-04-14 17:52:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.10)
2021-04-14 17:52:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.16)
2021-04-14 17:52:46 - custom_script - [INFO] - turbidostat dilution for vial 2
2021-04-14 17:53:06 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.25)
2021-04-14 17:53:25 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.25)
2021-04-14 17:53:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.16)
2021-04-14 17:54:05 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 23.01)
2021-04-14 17:54:26 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 22.92)
2021-04-14 17:54:45 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 22.84)
2021-04-14 17:55:06 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 22.69)
2021-04-14 17:55:26 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 22.54)
2021-04-14 17:55:46 - eVOLVER - [INFO] - actual temperature doesn't match configuration (yet? max deltaT is 22.43)
2021-04-14 17:56:04 - eVOLVER - [WARNING] - interrupt received, pausing experiment
2021-04-14 17:56:04 - eVOLVER - [INFO] - stopping all pumps
2021-04-14 17:56:05 - eVOLVER - [WARNING] - second interrupt received, terminating experiment
2021-04-14 17:56:05 - eVOLVER - [INFO] - stopping all pumps
2021-04-14 17:56:05 - eVOLVER - [WARNING] - experiment stopped, goodbye!
2021-04-14 17:56:05 - eVOLVER - [INFO] - stopping all pumps
